BaseUrl: "http://example.com"
LanguageCode: "zh-cn"
Title: "Beg"

Params:
  Author: "Wesley"
  DateForm: "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID: "Your ID."
  Facebook: "snowwindli@hotmail.com"
  Twitter: "Your ID."
  Github: "wei2009.li@gmail.com"
  ShowRelatedPost: True
  Disqus: "wesleywli"
  SyntaxHighlightTheme: "solarized_dark.min.css"

Indexes:
  tag: "tags"

permalinks:
  post: /blog/:year/:month/:day/:title/

MetadataFormat: "yaml"

